title: Joshua Vu # your name (or website title) here
logo: "/images/Josh.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Mission driven software developer with a passion for agile UI design, collaboration, and innovation.
  <br><br>
  I have always sought out opportunities that challenges me. Although my professional path has taken many twists and turns, from healthcare to creative marketing and software development, I’ve never stopped engaging my passion to help others and solve problems.
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
