title: Daeun Jung # your name (or website title) here
logo: "/images/Daeun_Jung.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://drive.google.com/file/d/1i7P1od4GzqkqcG2A3Lb4B7Q99hceoU3f/view?usp=sharing">View My CV</a> 
#  <br><br>
  <a href="daeun.jung@ewhain.net">View My email</a> 
#  <br><br>

# Second description 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
