title: Anthony Roman # your name (or website title) here
logo: "/images/portrait.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  As a data scientist with a strong passion for NLP, computer vision, and transformer models, I am currently pursuing a bachelor's degree in Data Science at Temple University, specializing in Genomics and Bioinformatics as well as Computer Science.
  <br><br>
  <a href="https://www.linkedin.com/in/anthony-joseph-roman">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-0HDL6ZHZG8 # your Google Analytics tracking ID here
