title: Yankee Majumder # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior Software engineer at Cognizant
  <br><br>
  As a Senior System Engineer, I have honed my skills in various technologies over the years. My expertise lies in Access Management, Incident and Request Management, Integration, System Support, Active Directory Cleanup, and Vulnerability Management. I excel in troubleshooting and optimizing End-User Computing solutions across a wide range of organizations. With a deep-rooted understanding of IT infrastructure, my specialization is in crafting secure and seamless environments that heighten user productivity and satisfaction. 6+ years of experience in IT Delivery, System/Device End user support,Identity Access Management, and Application support.
Dedicated and seasoned System Engineer with a proven track record of designing, implementing, and optimizing End-User Computing solutions for diverse organizations.
  <br><br>
  <a href="https://www.linkedin.com/in/yankee-majumder-6870ba134/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

