title: Amanda Crawford # your name (or website title) here
logo: "/images/profile_photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a tech polymath, researcher, and engineer with an interest in data science, artificial intelligence, distributed systems, and software testing. I have industry and academic experience using many different languages and tools including Python, Javascript, HTML/CSS, Ruby, C, Neo4j, Git, Selenium and cloud computing infrastructures including AWS and IOT. 
 <br><br>
  In addition, I have hands on experience with software testing and engineering, data science research, graph database modelling and algorithms, AWS, Python 2&3, Pandas, Jupyter, Sci-Kit, NodeJS, ES6, Angular 2, Ruby MiniTest, JUnit, Hadoop, Map Reduce, and distributed system modelling. 
  <br><br>
  <a href="https://www.linkedin.com/in/techacrawford/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
