title: Marco Arellano 📊 # your name (or website title) here
logo: "/images/photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  ¡Hola! Soy bachiller en Comunicaciones con experiencia en producción audiovisual y futuro Data Scientist. 
  Dataviz, R Stats y Tableau entusiasta. 
  Me apasiona la ciencia de datos, especialmente las áreas de visualización y storytelling. 
  Estoy a la búsqueda de nuevas oportunidades para desarrollar mis habilidades como científico de datos, soy responsable, dedicado y tenaz.
  <br><br>
  <a href="https://www.linkedin.com/in/marellanob/"> LinkedIn</a> 
  <a href="https://twitter.com/marellanob93"> Twitter</a> 
  
theme: jekyll-theme-minimal
