title: Mohammed Abu Jafar # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Hello everyone,

I hope this message finds you well. As some of you may know, my family and I recently relocated to Dublin, Ireland to support my wife's work business needs. I'm excited to announce that I've recently completed two certificates in data analysis from Google and Data Science from IBM, which have equipped me with a range of valuable skills in data visualization, machine learning, statistical analysis, and more.

With my education in chemical engineering and my experience in data analysis tools such as MySQL, Python, Power BI, statistics, data analysis foundations, and Access, I'm actively seeking entry-level data analyst positions in Ireland.

If anyone knows of any opportunities that might be a good fit for me, please don't hesitate to reach out. I'm passionate about working in my field, and I'm confident that my skills and experience would be an asset to any team. Thank you in advance for your support and help.
  <br><br>
  <a href="https://www.linkedin.com/in/mohammad-abu-jafar-22660520a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: 353732603 # your Google Analytics tracking ID here
