title: Daeun Jung # your name (or website title) here
logo: "/images/Daeun_Jung.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://drive.google.com/file/d/1i7P1od4GzqkqcG2A3Lb4B7Q99hceoU3f/view?usp=sharing">View My CV</a> 
  <br>
  <a href="https://www.linkedin.com/in/daeun-jung-6b86771a6/">View My linkedin</a> 
  <br>
  <a href="daeun.jung@ewhain.net">contact me by email</a> 
#  <br><br>
  location         : "South Korea"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:devinlifeidea@gmail.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://devinlife.com"
      
# Second description 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here



