title: John Wong # your name (or website title) here
logo: "/images/IMG_2937_circle_small.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I've consulted government agencies, legislators, and developers on macroeconomics, regulations, and development. As a data scientist, I use R and Python for machine learning, web scraping, forecasting, causal inference, and data visualization. As a public sector consultant, I also assess impact, benchmark policies, and engage stakeholders.
  <br>
  <br>
  <a href="https://www.linkedin.com/in/johnthwong/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-CXRL3XP9BW # your Google Analytics tracking ID here
