title: Daeun Jung # your name (or website title) here
logo: "/images/Daeun_Jung.jpg?raw=true" # your photo (or logo) here
email: "daeunj@umd.edu"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <a href="https://www.linkedin.com/in/daeun-jung-6b86771a6/">View My linkedin</a> 
  <br><br>
  Contact me by email : daeunj@umd.edu
    
# Second description 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


