title: Harry Waugh # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Computer Science graduate from the University of Bristol, with a passion for technology and a particular interest in HPC, 
  Computer Graphics and Deep Learning.
  <br><br>
  07714190277
  <br>
  hw16471@bristol.ac.uk
  <br><br>
  <a href="https://www.linkedin.com/in/harry-waugh-09a4b1152/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimals
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
