title: Hannes Dürr # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Industrial engineer and aspiring data analyst.<br>On a step-by-step journey mastering the art of telling stories with data. 
  <br><br>
  - 👋 Hi, I’m @duerrhannes<br>
  - 👀 I’m interested in rock climbing, mountaineering, financial markets, trains and, of course, data science<br>
  - 🌱 I’m currently improvng my python skills, trying to do some proper EDA and working to spruce up my visualizations<br>
  <br><br>
  <a href="https://linkedin.com/in/hannesduerr">View My LinkedIn Profile</a> 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme