title: Miguel Somarriba # your name (or website title) here
logo: "/images//50A65523-DE95-41C1-BBEA-21B01E8A9803-removebg-preview.png # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my portfolio! I am excited to showcase my skills and projects to potential employers and collaborators. With a passion for learning and a dedication to growing as a professional, I am eager to contribute to a team and make a positive impact in the industry. Thank you for taking the time to view my work, and I look forward to the opportunity to connect.
  <br><br>
  Diploma in Data Science from Concordia University, where I focused on modern concepts and technologies such as Python, MySQL/SQL, supervised/unsupervised learning, predictive modelling, and time series forecasting.
  <br><br>
  <a href="https://www.linkedin.com/in/miguel-somarriba/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
