title: Krystal Saverse # your name (or website title) here
logo: "/images/unnamed.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  4+ years GIS experience and 2+ years broadband experience. 
  Master of Science in Geospatial Technologies from the University of Oklahoma. 
  Bachelor of Arts in Geography from the University of Missouri.
  <br><br>
  I am currently the Broadband Data and GIS Analyst at Arizona Commerce Authority.  
  Previously position: Assistant Consultant for a fiber telecommunications 
  engineering firm, Imagery Analyst at MU's Center for Geospatial Intelligence, 
  Flight Operations Technician at the Arkansas Army Aviation Support Facility, 
  14+ years of service in the Army National Guard. 
  <br><br>
  <a href="https://www.linkedin.com/in/krystalsaverse">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
