title: Data to Decision 
       <br>
       by Jennifer Siwu 
 # your name (or website title) here
logo: "/images/P7240012.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my page! My name is Jennifer and I am currently pursuing a Master's degree in Analytics and Applied Statistics.
  Prior to this, I had a 2.5 years of experience in Supply Chain & Continuous Improvement Professional with background 
  in Analytics, Supply Planning, Demand Planning, Inventory Management, S&OP, and Workforce Operations.
  I leverage data and statistical concepts to analyze areas of improvement, root cause issues, prove hypothesis, and identify optimal solutions.
  I specialize in simplifying complex business problems and solutions to empower key process owners in making informed decisions.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/jennifer-siwu/">View My LinkedIn Profile</a> 

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
