title: Andrew Schell # your name (or website title) here
logo: "/images/11813209.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  An analytical undergrad with a specialty in computational linguistics My thesis is on cultural risk ratios that influence communication. No client code here
  <br><br>
  A nerd who is motivated the more often I am told "It can't be done"

  The difference between a bad programmer and a good one is whether he considers his code or his data structures more important. Linus Torvald the Grea
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  

theme: jekyll-theme-minimal
google_analytics: G-V7RG6RRLJT # your Google Analytics tracking ID here
=======
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme


