title: Rocio Soledad Radulescu
logo: "/images/logo_git.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Big data - Data engineer</b> 
  <br><br>
  I have been working as a data engineer in a consulting firm since October 2020 with cloud technologies.
  I currently work at Comafi Bank in Buenos Aires.
  I have also worked as a university teacher for 10 years in the field of databases of the degree in computer science 
  and with more than 10 years of experience managing databases of academic information.
  <a href="mailto:rsradulescu@gmail.com?Subject=Enlace%20portfolio">Email</a>
  <a href="https://www.linkedin.com/in/rsradulescu/">LinkedIn</a> 
theme: jekyll-theme-minimal
