title: CUSP Capstone Project # your name (or website title) here
logo: "/images/CUSP.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  NYU Capstone project by Nathan Caplan, Christine Chang, Rohun Iyer and Sarah Sachs 
  <br><br>
  Factors to Become an Innovation Hub 
  <br><br>
  <a href="https://github.com/rohuniyer/a_story_of_cities_and_patents">Project Github Repository</a> 
  <br><br>
  <a href="https://github.com/rohuniyer/a_story_of_cities_and_patents">Determinants of Innovation</a>
  <br><br>
  <a href="https://github.com/rohuniyer/a_story_of_cities_and_patents">Story Map</a>
  
theme: jekyll-theme-cayman
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
