title: Sophie Olsen # your name (or website title) here
logo: "/images/IMG_4722.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Python Developer 
  <br><br>
  Data Analytics
  <br><br>
  <a href="https://www.linkedin.com/in/sophie-olsen/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-169676435-1 # your Google Analytics tracking ID here
