title: Marco Arellano # your name (or website title) here
logo: "/images/photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  
  Comunicador y Futuro Data Scientist. Conocimiento en R y Tableau
  
  <br><br>
  <a href="https://www.linkedin.com/in/marellanob/"> LinkedIn </a> 
  <br><br>
  <a href="https://twitter.com/marellanob93"> Twitter </a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
