title: liyempo
logo: "/images/pfp.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I do not share my face or name due for privacy and safety
  But please feel free to email me for business inquiries!
  liyempo.karne@gmail.com
  <br><br>
  Liye will recieve a BFA in General Fine Arts with a minor in Game Design.
  Liye has experience with Unity, Plastic SCM, and the game development process
  within an academic setting. 
  <br><br>
  Social Media
  <br><br>
  <a href="https://www.instagram.com/liyempo/?hl=en">Instagram</a> 
  <br>
  <a href="https://www.tiktok.com/@liyempo">TikTok</a> 
  <br>
  <a href="https://liyempo.itch.io/">Itch.io</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

