title: \nMarco Arellano 游늵 # your name (or website title) here
logo: "/images/photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  
  춰Hola! Mi nombre es Marco. Soy comunicador audiovisual y futuro Data Scientist. 
  
  Desde chico me gustaron los rompecabezas y contar historias, para mi eso es la ciencia de datos la habilidad de mediante 
  data armar las piezas para contar la historia que los n칰meros nos quieren contar.
 
  Tengo m치s de 4 a침os de experiencia en producci칩n audiovisual, dise침o gr치fico y gesti칩n fotogr치fica de eventos deportivos.
  La estadistica y la ciencia de datos fue algo q
  
 
  <br><br>
  <a href="https://www.linkedin.com/in/marellanob/"> LinkedIn </a> 
  <br><br>
  <a href="https://twitter.com/marellanob93"> Twitter </a> 
  
theme: jekyll-theme-minimal
