title: Hannes Dürr # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Industrial engineer working in the railway industry. Aspiring data analyst. 
  <br><br>
  - 👋 Hi, I'm @duerrhannes<br>
  - 👀 I'm interested in rock climbing, mountaineering, financial markets, trains and, of course, data science<br>
  - 🌱 I'm currently improvng my python skills and working to spruce up crafting visualizations<br>
  <br><br>
  <a href="https://linkedin.com/in/hannesduerr">View My LinkedIn Profile</a> 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
