title: Zina Kurian # your name (or website title) here
logo: "/images/zinaspain2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My professional portfolio 
  <br><br>
  zinakurian@gmail.com
  <br>zkurian2@jhu.edu
  <br>
  @letsmapit
  
  <br><br>
  <a href="https://www.linkedin.com/in/zinakurian">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
