title: Vincent Chen # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I currently attend Westview High School as an incoming senior and am expected to graduate in 2023.
  <br><br>
  In my spare time I like to play guitar, hang out with friends, and exercise.
  <br><br>
  <a href="https://www.linkedin.com/in/vincent-chen-a89b63217/">My LinkedIn Profile!</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
