title: Daeun Jung # your name (or website title) here
logo: "/images/Daeun_Jung.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.dropbox.com/s/g1pmjop5ed5zi9i/daeunj_cv_v2.pdf?dl=0">View My CV</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/daeun-jung-6b86771a6/">View My LinkedIn Profile</a> 
#  <br><br>

# Second description 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
