title: Sarah Carpe # your name (or website title) here
logo: "/images/IMG_7905 (1).PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  UMBC Environmental Science B.S. May 2020. 
  2+ years expereince with GIS platforms, proficiency in ARCMap,
  beginner experience in R and QGIS. Research Assistant for USDA Forest Service.
  4+ years of experience in laboratory techniques, 
  mastery of many molecular biology techniques and lab management. Student Researcher at UMBC.
  <br><br>
  <a href="https://www.linkedin.com/in/sarah-carpe-10a128180">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.instagram.com/allthingswild.photos/">View My Instagram Profile</a>
  
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
