title: Sayash Raaj # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  IIT Madras 2023, Btech.
  <br><br>
  Amazon Int'l App Dev Winner 2017: http://bit.ly/2PRMDlp<br>
  Glorifire Entrepreneurship India Finalist: AI Sanitation Drone
  <br><br>
  <a href="https://www.linkedin.com/in/sayashraaj/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
