title: Marco Arellano 📊 # your name (or website title) here
logo: "/images/photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  ¡Hola! Soy comunicador y futuro Data Scientist. Dataviz, R Stats y Tableau entusiasta. 
  Soy graduado en Ciencias de la Comunicación, con experiencia en producción audiovisual, diseño gráfico y gestión fotográfica de eventos deportivos. 
  Actualmente me encuentro inmerso en el universo de ciencias de datos, aprendiendo y practicando. 
  Estoy recibiendo tutoría de una profesora de estadística, siguiendo el libro “Introduction to Modern Statistics” (Duke University) para avanzar mi preparación en este campo. 
  Me apasiona la ciencia de datos, especialmente las áreas de visualización y comunicación de resultados. Estoy a la búsqueda de nuevas oportunidades para desarrollar mis habilidades como científico de datos, soy responsable, dedicado y tenaz.
  <br><br>
  <a href="https://www.linkedin.com/in/marellanob/"> LinkedIn</a> 
  <br><br>
  <a href="https://twitter.com/marellanob93"> Twitter</a> 
  
theme: jekyll-theme-minimal
