title: Sarah Carpe # your name (or website title) here
logo: "/images/IMG_7905 (1).PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  UMBC Environmental Science B.S. 
  <br><br>
  2+ years expereince with GIS platforms: ArcGIS, QGIS, R.
  <br><br>
  3+ years experience with lab management and molecular biology techniques.
  <br><br>
  GIS Research Assistant for USDA Forest Service & Student Researcher at UMBC.
  <br><br>
  <a href="https://www.linkedin.com/in/sarah-carpe-10a128180">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.instagram.com/allthingswild.photos/">View My Instagram Profile</a>
  
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
