title: Venugopal # your name (or website title) here
logo: "/images/Venu-BW.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Google AIMLOps 
  <br><br>
    <a href="https://www.linkedin.com/in/venu-ai-mlops-sre/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: 269237966 # your Google Analytics tracking ID here
