title: <center>Tori Ford</center> # your name (or website title) here <br><br>
logo: "/images/profpic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  A collection of technical documentation, user guides, and professional writing. 
  <br><br>
  I want to make complex ideas accessible to wide audiences.
  <br><br>
  <a href="https://www.linkedin.com/in/tori-ford-155399a8">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
