title: Krystal Saverse # your name (or website title) here
logo: "/images/unnamed.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  4+ years GIS experience and 2+ years broadband experience. 
  Master of Science in Geospatial Technologies from the University of Oklahoma. 
  Bachelor of Arts in Geography from the University of Missouri.
  <br><br>
  Currently, I am the Broadband Data and GIS Analyst for Arizona Commerce Authority, the state's broadband office.  Previously, I held a position as Assistant Consultant for a fiber telecommunications engineering firm. I also worked as an Imagery Analyst at the Center for Geospatial Intelligence on the University of Missouri's campus. I've also worked as a Flight Operations Technician at the Arkansas Army Aviation Support Facility and have 14+ years of service in the Army National Guard. 
  <br><br>
  <a href="https://www.linkedin.com/in/krystalsaverse">View My LinkedIn Profile</a> 
  linkedin.com/in/krystalsaverse
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
