title: Krystal Saverse # your name (or website title) here
logo: "/images/unnamed.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  4+ years GIS experience and 2+ years broadband experience. 
  I am currently the Broadband Data and GIS Analyst at Arizona Commerce Authority. 
  <br><br>
  Master of Science in Geospatial Technologies from the University of Oklahoma. 
  Bachelor of Arts in Geography from the University of Missouri.
  <br><br>
<a href="https://www.linkedin.com/in/krystalsaverse">View My LinkedIn Profile</a> 
  <br><br>
<a href="https://drive.google.com/file/d/1L5tO_82-Op3cAvdqlaW4RrBqhACBxp9j/view">View My Resume</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
