title: Marco Arellano 游늵 # your name (or website title) here
logo: "/images/photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  춰Hola! Soy comunicador y futuro Data Scientist. Dataviz, R Stats y Tableau entusiasta. 
  Soy bachiller en Comunicaciones, con experiencia en producci칩n audiovisual, dise침o gr치fico y gesti칩n fotogr치fica de eventos deportivos. 
  Actualmente me encuentro inmerso en el universo de ciencias de datos, aprendiendo y practicando. Me apasiona la ciencia de datos, especialmente las 치reas de visualizaci칩n y storytelling. 
  Estoy a la b칰squeda de nuevas oportunidades para desarrollar mis habilidades como cient칤fico de datos, soy responsable, dedicado y tenaz.
  <br><br>
  <a href="https://www.linkedin.com/in/marellanob/"> LinkedIn</a> 
  <br><br>
  <a href="https://twitter.com/marellanob93"> Twitter</a> 
  
theme: jekyll-theme-minimal
