title: A Story of Cities and Patents # website title
description: > # your text below (remove <br> elements if you don't need line breaks)
  NYU Center for Urban Science and Progress
  <br><br>
  2019 Capstone Project:
  <br><br>
  <b>Nathan Caplan, Christine Chang, Rohun Iyer and Sarah Sachs</b>
  
 
theme: jekyll-theme-cayman
show_downloads: true
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
