title: Hiro Ito # your name (or website title) here
logo: "/images/hiro_ito.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p>Data Analyst & Frontend developer</p>
  <p><a href="https://www.linkedin.com/in/hiroakiito/">View My LinkedIn Profile</a></p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
