title: Rocio Soledad Radulescu
logo: "/images/logo_git.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Big data - Data engineer</b> 
  <br><br>
  <a href="https://www.linkedin.com/in/rsradulescu/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
