title: Gianluca Cientanni # your name (or website title) here
logo: "/images/profile_picture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! My name is Gianluca and I am currently a games developer!
  <br><br>
  <a href=https://www.linkedin.com/in/gianluca-cientanni-805160174/">View My LinkedIn Profile</a>
  <br><br>
  <a href=https://medium.com/@gianluca.cientanni/">View My Medium Articles</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
